version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install sqlalchemy psycopg2-binary psycopg2  -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip ${CODEBUILD_SRC_DIR}/src/handle_tweets_stream.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - echo "DONE!!"
