version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping deployment package..."
      - cp src/handle_tweets_stream.py lambda_function.py
      - cp -R src/libs libs
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - echo "DONE!!"

artifacts:
  files:
    - 'lambda_function.py'
    - 'libs/*'
    - 'libs/models/*'
  discard-paths: no
  name: handle_tweets_stream-$(date +%Y-%m-%d)