version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python3 -m pip install --upgrade pip
      - pip3 install pytest
  build:
    commands:
      - python -m pytest --junitxml=tta-tests-report/unit-tests.xml

reports:
  pytest_reports:
    files:
      - unit-tests.xml
    base-directory: tta-tests-report
    file-format: JUNITXML
